"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ProductService_1 = require("./ProductService");
var Product_1 = require("./Product");
var _productService = new ProductService_1.ProductService();
var products = _productService.getProducts();
var product1 = _productService.getById(1);
console.log("Ürünler listeleniyor");
console.log(products);
console.log("------------------");
console.log("Id=1 olan ürün listeleniyor");
console.log(product1);
var newProduct = new Product_1.Product();
newProduct.name = "Iphone 13";
newProduct.price = 6000;
newProduct.category = "Telefon";
_productService.saveProduct(newProduct);
products = _productService.getProducts();
console.log(products);
